<?php
/**
 * Created by Yxl.
 * User: <zccem@163.com>.
 * Date: 2019/2/19
 * Time: 15:07
 */

namespace frontend\controllers\user;

use Yii;
use yii\web\Controller;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class BaseController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (Yii::$app->user->isGuest) {
            return $this->redirect( ['/member/login'] );
        }
    }
}